### ISSUE TITLE
Errors in devdocs

### ISSUE THREAD

**Issue by XenGi** [coffeestats/coffeestats-attic#2]
[Devdocs page deployment](https://github.com/coffeestats/coffeestats/blob/master/devdocs/deployment.rst) refers to non Github repos and branches that doesn't exist on Github. Should be updated to actual status or even better branches should be made or cloned from original repo.

**Comment by noqqe** [comment]
Fixed in 4f84a90244f7f4b8639bc1a383c74861e1bf9d3b
